# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Alban Gaignard
tagline:          'My personal web pages'
description:      'PhD in Computer Science, CNRS engineer'
url:              http://albangaignard.github.io
baseurl:          /

author:
  name:           'Alban Gaignard'
  url:            

paginate:         5
paginate_path: "blog/page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
